recipe: default.v1
language: en
pipeline:
  - name: SingleStepLLMCommandGenerator
    llm:
      model: gpt-4

policies:
  - name: FlowPolicy
  - name: EnterpriseSearchPolicy
    vectore_store:
      type: "faiss"
      source: "./docs"
#  - name: IntentlessPolicy
#  - name: EnterpriseSearchPolicy
#  - name: RulePolicy

assistant_id: 20240921-152730-flush-track
